### ISSUE TITLE
drty-admin throws an exception on startproject

### ISSUE THREAD

**Issue by tutuca** [drtyhbo/drty#3]
I'm trying to get the latest HEAD to work, because the version I got after installing via npm throws [this message](https://gist.github.com/811887) after trying to :
      $ drty-admin startproject potaje:

**Comment by drtyhbo** [comment]
Hi tutuca, thanks for the bug report! Did you install drty from npm or a pull from the latest sources?

Edit: What issues are you encountering with the HEAD sources?

**Comment by tutuca** [comment]
I've installed from npm, i don't find a way to install it from a clone.

Maybe the whole issue is the version of node I'm using (0.3.7)

**Comment by drtyhbo** [comment]
The version of drty in npm was super old (0.0.1) so I just published the most recent version (0.1.3). Please see if that works better.

I have not update drty to node 0.3.7, but will do that asap.

**Comment by tutuca** [comment]
The version from a git clone, or the latest release on npm throws the same error that I've reported in issue #2. Looks like some dependency mismatch (namely request 1.2.0).

Hope you can make it work with the latest node... looks like node 0.4 is just around the corner, I definitely would like to use this approach instead of express or some other framework :)

**Comment by drtyhbo** [comment]
Hey tutuca, I pushed 0.1.4 of drty -- it fixes lots of issues. I tested the example with node 0.3.8 and everything looks good. If you have trouble with mysql-libmysqlclient, please make sure you've 'apt-get install libmysqlclient-dev'.

Please don't hesitate to let me know if you have any questions. Many of django's features are implemented and many are not. Parts of the documentation are up to date, much is not. It's all a work in progress, so please ask away!

**Comment by tutuca** [comment]
I can confirm that it's working with the latest node when I install from npm. 

Great work man!
